START_TOKEN = "<START>"
END_TOKEN = "<END>"
PAD_TOKEN = "<PAD>"
UNKOWN_TOKEN = "<UNKOWN>"
EMBEDDING_SIZE = 300
HIDDEN_SIZE = 256
NUM_LAYERS = 1
BATCH_SIZE = 32
NUM_EPOCHS = 10
LEARNING_RATE = 0.001


__all__ = ['START_TOKEN', 'END_TOKEN', 'PAD_TOKEN', 'UNKNOWN_TOKEN', 'EMBEDDING_SIZE', 
               'HIDDEN_SIZE', 'NUM_LAYERS', 'BATCH_SIZE', 'NUM_EPOCHS', 'LEARNING_RATE']